module.exports = {
  root: true,
  parser: "@typescript-eslint/parser",
  extends: [
    "airbnb",
    "airbnb/hooks",
    "plugin:@typescript-eslint/recommended",
    "plugin:jest/recommended",
    "plugin:jest/style",
    "plugin:jest-dom/recommended",
    "plugin:json/recommended",
    "plugin:jsx-a11y/recommended",
    "plugin:import/typescript",
    "plugin:react/recommended",
    "plugin:react-hooks/recommended",
    "plugin:typescript-sort-keys/recommended",
    "plugin:prettier/recommended",
  ],
  plugins: ["simple-import-sort", "sort-destructure-keys", "sort-keys-fix"],
  parserOptions: {
    ecmaVersion: "es2021",
    sourceType: "module",
    ecmaFeatures: {
      jsx: true,
    },
  },
  globals: {
    APP_VERSION: true,
  },
  env: {
    browser: true,
    "jest/globals": true,
    node: true,
  },
  settings: {
    react: {
      version: "detect",
    },
    "import/resolver": {
      typescript: {
        alwaysTryTypes: true,
      },
    },
  },
  rules: {
    "@typescript-eslint/ban-types": "off",
    "@typescript-eslint/no-shadow": ["off"],
    "@typescript-eslint/no-use-before-define": ["error"],
    "@typescript-eslint/switch-exhaustiveness-check": "error",
    camelcase: "off",
    "import/export": "off",
    "import/extensions": "off",
    "import/first": "error",
    "import/newline-after-import": "error",
    "import/no-cycle": "off",
    "import/no-duplicates": "error",
    "import/no-unresolved": "error",
    "jsx-a11y/anchor-is-valid": "off",
    "new-cap": "off",
    "no-alert": "error",
    "no-case-declarations": "off",
    "no-console": "error",
    "no-done-callback": "off",
    "no-nested-ternary": "off",
    "no-redeclare": ["error", { builtinGlobals: false }],
    "no-shadow": "off",
    "no-underscore-dangle": "off",
    "no-use-before-define": "off",
    "prefer-const": "error",
    "react/destructuring-assignment": "off",
    "react/display-name": "off",
    "react/jsx-filename-extension": "off",
    "react/jsx-props-no-spreading": "off",
    "react/prop-types": ["off"],
    "react/require-default-props": "off",
    "require-yield": "error",
    "simple-import-sort/exports": "error",
    "simple-import-sort/imports": "error",
    "sort-destructure-keys/sort-destructure-keys": 2,
    "sort-keys": [
      "error",
      "asc",
      { caseSensitive: true, natural: false, minKeys: 2 },
    ],
    "sort-keys-fix/sort-keys-fix": "warn",
  },
};
