import { ColorKeysType } from '../../colors/types'
import Calendar from './icons/calendar.svg'
import Call from './icons/call.svg'
import Camera from './icons/camera.svg'
import Cart from './icons/cart.svg'
import ChartBar from './icons/chartBar.svg'
import Chat from './icons/chat.svg'
import Check from './icons/check.svg'
import CheckCircle from './icons/checkCircle.svg'
import ChevronDown from './icons/chevronDown.svg'
import ChevronDownV2 from './icons/chevronDownV2.svg'
import ChevronLeft from './icons/chevronLeft.svg'
import ChevronLeftV2 from './icons/chevronLeftV2.svg'
import ChevronRight from './icons/chevronRight.svg'
import ChevronRightV2 from './icons/chevronRightV2.svg'
import ChevronUp from './icons/chevronUp.svg'
import ChevronUpV2 from './icons/chevronUpV2.svg'
import Clipboard from './icons/clipboard.svg'
import Close from './icons/close.svg'
import CloseCircle from './icons/closeCircle.svg'
import CloseCircleV2 from './icons/closeCircleV2.svg'
import CloseV2 from './icons/closeV2.svg'
import Cloud from './icons/cloud.svg'
import CloudDone from './icons/cloudDone.svg'
import CloudDownload from './icons/cloudDownload.svg'
import CloudUpload from './icons/cloudUpload.svg'
import ColorPicker from './icons/colorPicker.svg'
import Components from './icons/components.svg'
import Computer from './icons/computer.svg'
import Copy from './icons/copy.svg'
import CreditCard from './icons/creditCard.svg'
import Delete from './icons/delete.svg'
import Deposit from './icons/deposit.svg'
import Download from './icons/download.svg'
import Edit from './icons/edit.svg'
import Education from './icons/education.svg'
import Email from './icons/email.svg'
import Error from './icons/error.svg'
import Exchange from './icons/exchange.svg'
import ExpandLess from './icons/expandLess.svg'
import ExpandMore from './icons/expandMore.svg'
import Explore from './icons/explore.svg'
import FaceId from './icons/faceId.svg'
import FavoriteFilled from './icons/favoriteFilled.svg'
import FavoriteOutline from './icons/favoriteOutline.svg'
import Filter from './icons/filter.svg'
import Fingerprint from './icons/fingerprint.svg'
import Flag from './icons/flag.svg'
import FlashOff from './icons/flashOff.svg'
import FlashOn from './icons/flashOn.svg'
import Fullscreen from './icons/fullscreen.svg'
import FullscreenExit from './icons/fullscreenExit.svg'
import Globe from './icons/globe.svg'
import GoogleTranslate from './icons/googleTranslate.svg'
import Hardware from './icons/hardware.svg'
import History from './icons/history.svg'
import Home from './icons/home.svg'

export type IconNameType =
  | 'activity'
  | 'airdrop'
  | 'alert'
  | 'blockchain'
  | 'android'
  | 'apple'
  | 'arrowDown'
  | 'arrowLeft'
  | 'arrowRight'
  | 'backspaceAndroid'
  | 'arrowUp'
  | 'backup'
  | 'bank'
  | 'blockchainCircle'
  | 'calendar'
  | 'call'
  | 'camera'
  | 'cart'
  | 'chartBar'
  | 'chat'
  | 'check'
  | 'checkCircle'
  | 'chevronDown'
  | 'chevronDownV2'
  | 'chevronLeft'
  | 'chevronLeftV2'
  | 'chevronRight'
  | 'chevronRightV2'
  | 'chevronUp'
  | 'chevronUpV2'
  | 'clipboard'
  | 'close'
  | 'closeCircle'
  | 'closeCircleV2'
  | 'closeV2'
  | 'cloud'
  | 'cloudDone'
  | 'cloudDownload'
  | 'cloudUpload'
  | 'colorPicker'
  | 'components'
  | 'computer'
  | 'copy'
  | 'creditCard'
  | 'delete'
  | 'deposit'
  | 'download'
  | 'edit'
  | 'education'
  | 'email'
  | 'error'
  | 'exchange'
  | 'expandLess'
  | 'expandMore'
  | 'explore'
  | 'faceId'
  | 'favoriteFilled'
  | 'favoriteOutline'
  | 'filter'
  | 'fingerprint'
  | 'flag'
  | 'flashOff'
  | 'flashOn'
  | 'fullscreen'
  | 'fullscreenExit'
  | 'globe'
  | 'googleTranslate'
  | 'hardware'
  | 'history'
  | 'home'
  | 'identification'
  | 'image'
  | 'information'
  | 'key'
  | 'keyboard'
  | 'laptop'
  | 'legal'
  | 'lineChartUp'
  | 'link'
  | 'listBullets'
  | 'lockClosed'
  | 'lockOpen'
  | 'logout'
  | 'marketUp'
  | 'menu'
  | 'microphone'
  | 'minusCircle'
  | 'moneyUsd'
  | 'moreHorizontal'
  | 'moreVertical'
  | 'newWindow'
  | 'nft'
  | 'notificationOff'
  | 'notificationOn'
  | 'pending'
  | 'people'
  | 'phone'
  | 'pin'
  | 'placeholder'
  | 'playCircle'
  | 'plus'
  | 'plusCircle'
  | 'portfolio'
  | 'present'
  | 'print'
  | 'private'
  | 'qrCode'
  | 'question'
  | 'questionCircle'
  | 'receive'
  | 'receiveV2'
  | 'refresh'
  | 'repeat'
  | 'rewards'
  | 'rewardsCircle'
  | 'search'
  | 'sell'
  | 'send'
  | 'sendV2'
  | 'settings'
  | 'shareAndroid'
  | 'shareIos'
  | 'shield'
  | 'signout'
  | 'subdirectory'
  | 'support'
  | 'swap'
  | 'sync'
  | 'tag'
  | 'timeout'
  | 'tor'
  | 'trade'
  | 'triangleDown'
  | 'triangleUp'
  | 'unfoldLess'
  | 'unfoldMore'
  | 'user'
  | 'userAdd'
  | 'verified'
  | 'visibilityOff'
  | 'visibilityOn'
  | 'wallet'
  | 'withdraw'

export type IconSizesType = 'sm' | 'md' | 'lg'

export type IconComponentProps = {
  color?: ColorKeysType
  fill?: string
  name: IconNameType
  size?: IconSizesType
}
