import { ColorKeysType } from '../../colors/types'
import Calendar from './icons/calendar.svg'
import Call from './icons/call.svg'
import Camera from './icons/camera.svg'
import Cart from './icons/cart.svg'
import ChartBar from './icons/chartBar.svg'
import Chat from './icons/chat.svg'
import Check from './icons/check.svg'
import CheckCircle from './icons/checkCircle.svg'
import ChevronDown from './icons/chevronDown.svg'
import ChevronDownV2 from './icons/chevronDownV2.svg'
import ChevronLeft from './icons/chevronLeft.svg'
import ChevronLeftV2 from './icons/chevronLeftV2.svg'
import ChevronRight from './icons/chevronRight.svg'
import ChevronRightV2 from './icons/chevronRightV2.svg'
import ChevronUp from './icons/chevronUp.svg'
import ChevronUpV2 from './icons/chevronUpV2.svg'
import Clipboard from './icons/clipboard.svg'
import Close from './icons/close.svg'
import CloseCircle from './icons/closeCircle.svg'
import CloseCircleV2 from './icons/closeCircleV2.svg'
import CloseV2 from './icons/closeV2.svg'
import Cloud from './icons/cloud.svg'
import CloudDone from './icons/cloudDone.svg'
import CloudDownload from './icons/cloudDownload.svg'
import CloudUpload from './icons/cloudUpload.svg'
import ColorPicker from './icons/colorPicker.svg'
import Components from './icons/components.svg'
import Computer from './icons/computer.svg'
import Copy from './icons/copy.svg'
import CreditCard from './icons/creditCard.svg'

export type IconNameType =
  | 'activity'
  | 'airdrop'
  | 'alert'
  | 'blockchain'
  | 'android'
  | 'apple'
  | 'arrowDown'
  | 'arrowLeft'
  | 'arrowRight'
  | 'backspaceAndroid'
  | 'arrowUp'
  | 'backup'
  | 'bank'
  | 'blockchainCircle'
  | 'calendar'
  | 'call'
  | 'camera'
  | 'cart'
  | 'chartBar'
  | 'chat'
  | 'check'
  | 'checkCircle'
  | 'chevronDown'
  | 'chevronDownV2'
  | 'chevronLeft'
  | 'chevronLeftV2'
  | 'chevronRight'
  | 'chevronRightV2'
  | 'chevronUp'
  | 'chevronUpV2'
  | 'clipboard'
  | 'close'
  | 'closeCircle'
  | 'closeCircleV2'
  | 'closeV2'
  | 'cloud'
  | 'cloudDone'
  | 'cloudDownload'
  | 'cloudUpload'
  | 'colorPicker'
  | 'components'
  | 'computer'
  | 'copy'
  | 'creditCard'

export type IconSizesType = 'sm' | 'md' | 'lg'

export type IconComponentProps = {
  color?: ColorKeysType
  fill?: string
  name: IconNameType
  size?: IconSizesType
}
