name: pull-request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.16]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build icons
        run: yarn workspace @blockchain-com/icons build

      - name: TestCoverage
        id: testCoverage
        uses: anuraag016/Jest-Coverage-Diff@master
        with:
          runCommand: 'yarn workspace @blockchain-com/constellation test --coverage --coverageReporters="json-summary" && mv packages/constellation/coverage/coverage-summary.json ./'
          delta: 0.5

      - name: Lint Constellation code
        run: yarn workspace @blockchain-com/constellation lint

      - name: Test Constellation code
        run: yarn workspace @blockchain-com/constellation test

      - name: Build Constellation code
        run: yarn workspace @blockchain-com/constellation build
